components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-configs-values:
            path: /configs/values
            method: POST
            task_processor: main-task-processor

        handler-admin-v1-configs:
            path: /admin/v1/configs
            method: POST
            task_processor: main-task-processor

        handler-admin-v1-configs-delete:
            path: /admin/v1/configs/delete
            method: POST
            task_processor: main-task-processor

        testsuite-support: {}

        configs-cache:
            pgcomponent: settings-database
            update-interval: 10s
            full-update-interval: 1m
            update-correction: 2s
            update-jitter: 1s
            chunk-size: 100

        settings-database:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true

        http-client:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: mockserver/testpoint
            throttling_enabled: false
